server:
  port: 8080
  servlet:
    context-path: /api

spring:
  datasource:
    url: jdbc:h2:mem:cities
    driver-class-name: org.h2.Driver
    username: city
    password: city
    initialize: true
  h2:
    console:
      enabled: true
      path: /h2-console
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

openweathermap:
  api:
    key: 9987abbe6a7f2aef9db698504c2361a1
  city:
    temp:
      url: https://api.openweathermap.org/data/2.5/weather
    list:
      filename: city.list.json